cp MyCABA.EXT.x 1bs/
cp NewFitProg.x 1bs/
cp runcaba.sh 1bs/
cp MyCABA.EXT.x 1bs/oneopenchannel/
cp NewFitProg.x 1bs/oneopenchannel/
cp runcaba.sh 1bs/oneopenchannel/
cp MyCABA.EXT.x 1bs/twoopenchannels/
cp NewFitProg.x 1bs/twoopenchannels/
cp runcaba.sh 1bs/twoopenchannels/
cp MyCABA.EXT.x 2bs/
cp NewFitProg.x 2bs/
cp runcaba.sh 2bs/
cp MyCABA.EXT.x 2bs/oneopenchannel/
cp NewFitProg.x 2bs/oneopenchannel/
cp runcaba.sh 2bs/oneopenchannel/
cp MyCABA.EXT.x 2bs/twoopenchannels/
cp NewFitProg.x 2bs/twoopenchannels/
cp runcaba.sh 2bs/twoopenchannels/
cp MyCABA.EXT.x 3bs/
cp NewFitProg.x 3bs/
cp runcaba.sh 3bs/
cp MyCABA.EXT.x 3bs/oneopenchannel/
cp NewFitProg.x 3bs/oneopenchannel/
cp runcaba.sh 3bs/oneopenchannel/
cp MyCABA.EXT.x 3bs/twoopenchannels/
cp NewFitProg.x 3bs/twoopenchannels/
cp runcaba.sh 3bs/twoopenchannels/
